name: CI

on: [pull_request]

defaults:
  run:
    shell: bash

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    name: ${{ fromJson('{"macos-latest":"macOS","windows-latest":"Windows","ubuntu-latest":"Ubuntu"}')[matrix.os] }}
    continue-on-error: false
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Run tests
        run: |
          python -m pip install pytest
          pytest test_truststore.py
