name: PyPI

on:
  push:
    tags: v[0-9]+.[0-9]+.[0-9]+

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Build dists
        shell: bash
        run: |
          python -m pip install -U build
          python -m build

      - name: Publish dists to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
